#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_STRING 50
#define MAX_STRING_DESIGNACAO 50
#define MAX_STRING_MODELO 50
#define MAX_BICICLETAS 15
#define MAX_UTENTES 50
#define MAX_CODIGO_UTENTE 999999999
#define MAX_TELEFONE 999999999


#define MAX_ESTUDANTES 100

#define MAX_EMPRESTIMOS 100 // Temporario
#define MAX_ID_EMPRESTIMOS 99999 // Temporario


#endif // CONSTANTES_H_INCLUDED
