#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define MAX_STRING 50
#define MAX_STRING_DESIGNACAO 50
#define MAX_STRING_MODELO 50
#define MAX_BICICLETAS 15
#define MAX_UTENTES 50

#define MAX_ESTUDANTES 100



#endif // CONSTANTES_H_INCLUDED
